config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]
  resource :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  delegate :username, to: :user

  def self.tagged_with(name)
    Tag.find_by(name: name).posts
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create 
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggins
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy

  # active relationship
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # passive relations
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  

  # follow and unfollow user method            
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end          

  # mount carrierwave
  mount_uploader :avatar, AvatarUploader 

  # validate username
  validates :username, presence: true

  # crop image
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configured_permitted_parameters, if: :devise_controller?

  def current_user?(user)
    current_user.id == user.id
  end

  helper_method :current_user?

  protected

    def configured_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)}
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :remember_me)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :avatar, :emmail, :password, :password_confirmation, :current_password)}
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :all_tags)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def create
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    current_user.unfollow(@user)
    redirect_to @user
  end

  private
    def set_user
      @user = User.find(params[:user_id])  
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :check_authorization, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      if params[:user][:avatar].present?
        render :crop
      else
      redirect_to @user, notice: "Sucessfully updated user."
      end
    else
      flash.now[:alert] = "Something went wrong. Please try again"
      render :edit, alert: "Could not update, Please try again"
    end
  end

  private
    
    def set_user
      @user = User.find(params[:id])
    end

    def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end     
    end

  

    def user_params
      params.require(:user).permit(:username, :avatar, :description, :crop_x, :crop_y, :crop_w, :crop_h )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user, options = { size: 80 } )
    size = options[:size]
    if user.avatar?
      image_tag user.avatar_url(:thumb), width: size
    else
      image_tag "default-avatar.png", width: size
    end
  end

  def user_name?
    if current_user.username
        current_user.username
      else
        current_user.email
    end
  end

end

app/views/home/index.html.erb
<div class="row">
<div class="col-md-6 offset-md-1">
<%= render @posts %>
</div>

<div class="col-md-4 sidebar">
  <h4 class="featured-tag border-top">featured tags</h4>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'shared/main_nav' %>
    
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="container-fluid main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post-panel"> 
  <span class="recomended">Featured and recomended by others</span>
  <div class="post-header">
    <div class="post-avatar">
      <%= user_avatar(post.user, size: 40)%>
    </div>
    <div class="post-info">
      <%= link_to post.username, post.user %>
      <br>
      <span class="time-created">
        <%= time_ago_in_words(post.created_at) %> ago 
      </span>
    </div>
  </div>
  <div class="post-content">
    <%= post.title %>
    <br>
    <%= post.body%>
    <br>
    <%= post.all_tags %>
  </div>
  <div class="post-action clearfix">
    <a class="float-left" href="#">link</a>
    <a class="float-right" href="#">11 response</a>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<% if @post.errors.any? %>
  <div class="error">
    <h2>
      <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
    </h2>
    <ul>
      <% @post.errors.full_messages.each do |m|%>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.label :all_tags %>
  <%= f.text_field :all_tags%>
  <%= f.submit "Publish" %>
<% end %>

app/views/shared/_main_nav.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid col-md-10 offset-md-1 nav-container">
        <%= link_to 'Home', root_path, class: "navbar-brand" %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "Write a story", new_post_path, class: "nav-link story-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to(user_avatar(current_user, size: 40), current_user, class: "nav-link avatar") %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link session-link' %></a>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login | Signup', new_user_session_path,  class: 'nav-link session-link' %>
            </li>
          <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/users/crop.html.erb
<div class='row'>
  <div class='col-xs-8'>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Crop Avatar</h3>
      </div>
      <div class="panel-body">
        <%= image_tag @user.avatar_url(:large), id: "cropbox" %>
        <br>
        <%= form_for(@user) do |f| %>
          <% %w[x y w h].each do |attribute| %>
            <%= f.hidden_field "crop_#{attribute}" %>
          <% end %>

          <div class="form-actions">
            <%= f.button %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

  <div class='col-xs-4'>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Preview</h3>
      </div>
      <div class="panel-body">
        <div style="width:100px; height:100px; overflow:hidden">
          <%= image_tag @user.avatar.url(:large), id: "preview" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Edit User Profile</h1>

    <%= form_for(@user) do |f| %>
      <%= f.file_field :avatar %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.submit "Save changes"%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>New Username</h1>
    <%= image_tag @user.avatar_url(:thumb) if @user.avatar? %>
    <br />
    <%= @user.username %>
    <br />
    <%= @user.description %>
    <% if user_signed_in? && current_user?(@user) %>
     <%= link_to "Edit profile", edit_user_path(@user), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<% if user_signed_in? && !current_user?(@user) %>
  <% if current_user.following?(@user)%>
    <%= button_to "Unfollow", relationships_path(user_id: @user.id), method: :delete, class: "btn btn-default" %>
  <% else %>
    <%= button_to "Follow", relationships_path(user_id: @user.id), class: "btn btn-primary" %>
  <% end %>
<% end %>